on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n bigBangContainer -g bigBangContainer8cef-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n bigBangContainer --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n bigBangContainer --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n bigBangContainer --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: bigbangcontainer.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t bigbangcontainer.azurecr.io/akscluster:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push bigbangcontainer.azurecr.io/akscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_akscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-cluster93db | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-cluster93db`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-cluster93db
        container-registry-url: bigbangcontainer.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-cluster93db
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          bigbangcontainer.azurecr.io/akscluster:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdockerauth   
